### ISSUE TITLE
Does not work on FreeBSD

### ISSUE THREAD

**Issue by RafalLukawiecki** [tmux-plugins/tmux-online-status#11]
..because ping syntax is incorrectly assumed to be Linux-like, while it is macOS-like, as Darwin is a BSD-based system.

I have submitted PR #10 fixing this, but I see it has not been actioned. Are you interested in PRs or is this an abandoned or perhaps a personal project? I ask, because another new project is awaiting this PR, see https://github.com/samoshkin/tmux-config/pull/2

Many thanks,
Rafal

**Comment by bruno-** [comment]
The PR is merged now. Thank you.

**Comment by RafalLukawiecki** [comment]
Many thanks, @bruno-.
